Models/Entities/Author.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BookAuthorM2MApp.Models.Entities;

public class Author
{
    public int Id { get; set; }
    [StringLength(128)]
    public string? FirstName { get; set; } = string.Empty;
    [Required, StringLength(128)]
    public string LastName { get; set; } = string.Empty;
    [DisplayName("Number of Books")]
    public ICollection<Book> Books { get; set; } = new List<Book>();
}

Models/Entities/Book.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BookAuthorM2MApp.Models.Entities;

public class Book
{
    public int Id { get; set; }
    [Required, StringLength(256)]
    public string Title { get; set; } = string.Empty;
    public int PublicationYear { get; set; } = 0;
    [DisplayName("Number of Authors")]
    public ICollection<Author?> Authors { get; set; } = new List<Author?>();
}

Models/Entities/BookAuthor.cs
namespace BookAuthorM2MApp.Models.Entities;

public class BookAuthor
{
    public int Id { get; set; }
    public int AuthorId { get; set; }
    public Author? Author { get; set; }
    public int BookId { get; set; }
    public Book? Book { get; set; }
}

Models/ErrorViewModel.cs
namespace BookAuthorM2MApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AuthorController.cs
using BookAuthorM2MApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace BookAuthorM2MApp.Controllers;

public class AuthorController : Controller
{
    private readonly IAuthorRepository _authorRepo;

    public AuthorController(IAuthorRepository authorRepo)
    {
        _authorRepo = authorRepo;
    }

    public async Task<IActionResult> Index()
    {
        return View(await _authorRepo.ReadAllAsync());
    }
}

Controllers/BookAuthorController.cs
using BookAuthorM2MApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace BookAuthorM2MApp.Controllers;

public class BookAuthorController : Controller
{
    private readonly IBookAuthorRepository _bookAuthorRepo;
    private readonly IBookRepository _bookRepo;
    private readonly IAuthorRepository _authorRepo;

    public BookAuthorController(IBookAuthorRepository bookAuthorRepo,
        IBookRepository bookRepo,
        IAuthorRepository authorRepo)
    {
        _bookAuthorRepo = bookAuthorRepo;
        _bookRepo = bookRepo;
        _authorRepo = authorRepo;
    }

    public async Task<IActionResult> AssignAuthor([Bind(Prefix = "Id")] int bookId)
    {
        var authors = await _authorRepo.ReadAllAsync();
        ViewData["Book"] = bookId;
        return View(authors);
    }
    public async Task<IActionResult> AssignToBook([Bind(Prefix = "Id")] int bookId, int authorid)
    {
        await _bookAuthorRepo.Create(bookId, authorid);
        return RedirectToAction("Index", "Book");
    }
}

Controllers/BookController.cs
using BookAuthorM2MApp.Services;
using Microsoft.AspNetCore.Mvc;

namespace BookAuthorM2MApp.Controllers;

public class BookController : Controller
{
    private readonly IBookRepository _bookRepo;

    public BookController(IBookRepository bookRepo)
    {
        _bookRepo = bookRepo;
    }

    public async Task<IActionResult> Index()
    {
        return View(await _bookRepo.ReadAllAsync());
    }
}

Controllers/HomeController.cs
using BookAuthorM2MApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BookAuthorM2MApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Author/Index.cshtml
@model IEnumerable<BookAuthorM2MApp.Models.Entities.Author>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Books)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Books.Count)
            </td>
            <td>
                    <a asp-action="assignauthor" asp-controller="BookAuthor" asp-route-id="@Model!.Id">
                        Assign Author
                    </a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Book/Index.cshtml
@model IEnumerable<BookAuthorM2MApp.Models.Entities.Book>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublicationYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Authors)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PublicationYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Authors.Count)
            </td>
            <td>
                <a asp-action="assignauthor" asp-controller="BookAuthor">
                    Assign Author
                </a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/BookAuthor/AssignAuthor.cshtml
@model IEnumerable<BookAuthorM2MApp.Models.Entities.Author>

@{
    ViewData["Title"] = "AssignAuthor";
    var book = ViewData["Book"];
}

<h1>AssignAuthor</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.ActionLink("Assign", "AssignToBook", new {  id=book,authorid=item.Id  })
                </td>
            </tr>
        }
    </tbody>
</table>

Views/BookAuthor/AssignToBook.cshtml
@model IEnumerable<BookAuthorM2MApp.Models.Entities.Book>

@{
    ViewData["Title"] = "AssignBook";
    var author = ViewData["Author"];
}

<h1>AssignBook</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublicationYear)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PublicationYear)
                </td>
                <td>
                    @Html.ActionLink("Assign", "AssignToAuthor", new {  id=author, authorid=item.Id  })
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookAuthorM2MApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookAuthorM2MApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookAuthorM2MApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Book Index</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Author" asp-action="Index">Author Index</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BookAuthorM2MApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>